USE [TD5R1]
GO

/****** Object:  Table [dbo].[AREA_LINES]    Script Date: 08.09.2015 3:56:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AREA_LINES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[lat] [decimal](28, 10) NOT NULL,
	[lon] [decimal](28, 10) NOT NULL,
	[order_num] [int] NOT NULL,
	[tarif_id] [int] NOT NULL,
	[tplan_id] [int] NOT NULL,
	[outher_tarid] [int] NOT NULL,
	[outher_tplid] [int] NOT NULL,
 CONSTRAINT [PK_AREA_LINES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_lat]  DEFAULT ((0)) FOR [lat]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_lon]  DEFAULT ((0)) FOR [lon]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_Table_1_order]  DEFAULT ((0)) FOR [order_num]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_tarif_id]  DEFAULT ((-1)) FOR [tarif_id]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_tplan_id]  DEFAULT ((-1)) FOR [tplan_id]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_outher_tarid]  DEFAULT ((-1)) FOR [outher_tarid]
GO

ALTER TABLE [dbo].[AREA_LINES] ADD  CONSTRAINT [DF_AREA_LINES_outher_tplid]  DEFAULT ((-1)) FOR [outher_tplid]
GO


