USE [TD5R1]
GO

/****** Object:  Table [dbo].[ORDER_OPTION]    Script Date: 09/12/2014 12:08:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON 
GO

CREATE TABLE [dbo].[ORDER_OPTION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OPTION_NAME] [varchar](255) NOT NULL,
	[OSUMM_COEFF] [decimal](28, 10) NOT NULL,
	[OS_COMPOSED] [decimal](28, 10) NOT NULL,
 CONSTRAINT [PK_ORDER_OPTION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ORDER_OPTION] ADD  CONSTRAINT [DF_ORDER_OPTION_OPTION_NAME]  DEFAULT ('Без названия') FOR [OPTION_NAME]
GO

ALTER TABLE [dbo].[ORDER_OPTION] ADD  CONSTRAINT [DF_ORDER_OPTION_OSUMM_COEFF]  DEFAULT ((1)) FOR [OSUMM_COEFF]
GO

ALTER TABLE [dbo].[ORDER_OPTION] ADD  CONSTRAINT [DF_ORDER_OPTION_OS_COMPOSED]  DEFAULT ((0)) FOR [OS_COMPOSED]
GO


