CREATE TABLE [dbo].[TD_EVENTS](
	[EVENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CDATE] [datetime] NOT NULL,
	[ETYPE_ID] [int] NOT NULL,
	[DRIVER_ID] [int] NOT NULL,
	[ORDER_ID] [int] NOT NULL,
	[SECTOR_ID] [int] NOT NULL,
	[CLOSED] [smallint] NOT NULL,
	[EDATE] [datetime] NOT NULL,
	[DESCRIPTION] [varchar](2000) NOT NULL,
	[ADRES] [varchar](255) NOT NULL,
	[PHONE] [varchar](255) NOT NULL,
	[DR_NUM] [int] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_CDATE]  DEFAULT (getdate()) FOR [CDATE]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_ETYPE_ID]  DEFAULT ((-1)) FOR [ETYPE_ID]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_DRIVER_ID]  DEFAULT ((-1)) FOR [DRIVER_ID]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_ORDER_ID]  DEFAULT ((-1)) FOR [ORDER_ID]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_SECTOR_ID]  DEFAULT ((-1)) FOR [SECTOR_ID]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_CLOSED]  DEFAULT ((0)) FOR [CLOSED]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_EDATE]  DEFAULT (getdate()) FOR [EDATE]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_DESCRIPTION]  DEFAULT ('Без описания') FOR [DESCRIPTION]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_ADRES]  DEFAULT ('') FOR [ADRES]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_PHONE]  DEFAULT ('') FOR [PHONE]
GO

ALTER TABLE [dbo].[TD_EVENTS] ADD  CONSTRAINT [DF_TD_EVENTS_DR_NUM]  DEFAULT ((-1)) FOR [DR_NUM]
GO


