USE [TD5R1]
GO

/****** Object:  Table [dbo].[ORDER_TARIF]    Script Date: 09/12/2014 10:35:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDER_TARIF](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TARIF_NAME] [varchar](255) NOT NULL,
	[TIME_TARIF] [decimal](28, 10) NOT NULL,
	[TMETER_TARIF] [decimal](28, 10) NOT NULL,
 CONSTRAINT [PK_ORDER_TARIF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO 

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ORDER_TARIF] ADD  CONSTRAINT [DF_ORDER_TARIF_TARIF_NAME]  DEFAULT ('Без названия') FOR [TARIF_NAME]
GO

ALTER TABLE [dbo].[ORDER_TARIF] ADD  CONSTRAINT [DF_ORDER_TARIF_TIME_TARIF]  DEFAULT ((0)) FOR [TIME_TARIF]
GO

ALTER TABLE [dbo].[ORDER_TARIF] ADD  CONSTRAINT [DF_ORDER_TARIF_TMETER_TARIF]  DEFAULT ((0)) FOR [TMETER_TARIF]
GO


